name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

env:
  TYPESENSE_NODE: ${{ vars.TYPESENSE_NODE }}
  TYPESENSE_ADMIN_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: BS fix from https://github.com/typesense/docusaurus-theme-search-typesense/issues/23
        run: sed -i '/process.env.DEBUG = namespaces;/c\// process.env.DEBUG = namespaces;' ./node_modules/debug/src/node.js
      - name: Build website
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
      #     publish_dir: ./build

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          # The secret containing your Typesense API key. Required.
          api-key: ${{ env.TYPESENSE_ADMIN_API_KEY }}
          
          # The hostname or IP address of your Typesense server. Required.
          host: ${{ env.TYPESENSE_NODE }}
          
          # The port on which your Typesense server is listening. Optional. Default: 8108.
          port: 443
          
          # The protocol to use when connecting to your Typesense server. Optional. Default: http.
          protocol: https
          
          # The path to your DocSearch config file. Optional. Default: docsearch.config.json.
          config: docsearch.config.json
