name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0/1 * * 1-5'
  workflow_dispatch:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

env:
  ALGOLIA_APP_ID: ${{vars.ALGOLIA_APP_ID}}
  ALGOLIA_API_KEY: ${{vars.ALGOLIA_API_KEY}}
  ALGOLIA_INDEX_NAME: ${{vars.ALGOLIA_INDEX_NAME}}

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Bootstrap environment
        run: ./scripts/bootstrap.sh
      - name: Build website
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build

  algolia_recrawl:
    name: Algolia Recrawl
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      # We don't know when the site will be deployed, we just wait a few seconds
      # Better solutions can be found
      - name: Sleep for 30s
        run: sleep 30

      - name: Github-pages-MAIN => Algolia crawler creation and recrawl (Push on Main branch)
        uses: algolia/algoliasearch-crawler-github-actions@v1
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-name: ${{ secrets.CRAWLER_NAME }}
          algolia-app-id: ${{ vars.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ vars.ALGOLIA_API_KEY }}
          site-url: ${{ vars.SITE_URL }}
          override-config: false